### ISSUE TITLE
Introduce fast-path fallback

### ISSUE THREAD

**Issue by fridex** [selinon/selinon#1]
Currently, the dispatcher runs defined fallbacks only if there is some failure in the flow _and there are no active nodes_. This can be optimized by introducing "fast-path fallbacks". What we can do:
1. we already have a tree that is created of all possible permutations for defined failures
2. if there is a path from the current failureNode to another failureNode using currently active node in the system or it's (indirect) transitive child, we cannot run fallback, otherwise we can

Here is an example:

Let's say we have following dependencies defined for a flow in YAML file, where T1..3 are tasks (applicable for subflows as well).

``` yaml
from:
to:
 - T1
 - T2
 - T3
failures:
  - nodes:
    - T1
    - T2
    fallback:
    - T4

  - nodes:
    - T1
    fallback:
    - T4
```
1. If T1 failes and T2, T3 are still active, we have to wait
2. If T1 fails, T2 is finished successfully and T3 is still active, we can schedule T4 according to the second fallback
3. If T1, T2 fail and T3 is still active, we can schedule T4 according to the first fallback

What needs to be kept in mind:
- we have to inspect all possible subsequent nodes that can be scheduled - all transitive, even indirect
- we have to inspect all possible recursive dependencies in flows - we can detect recursion which would block fast-path evaluation as optimization
