### ISSUE TITLE
Let a flow fail even if fallback was run

### ISSUE THREAD

**Issue by fridex** [selinon/selinon#21]
It would be nice to let a flow fail even if there was a failure in the flow and a fallback was started:

```yaml
failures:
  - nodes:
     - task1
    fallback:
     - task1_fallback
    propagate_failure: true
```
