### ISSUE TITLE
Enhance built-in predicates

### ISSUE THREAD

**Issue by fridex** [selinon/selinon#22]
There is a possibility of enhancing built in predicates by predicates that would inspect parent or failure nodes from flows. E.g.:

```yaml
 propagate_compound_parent: flow1
 edges:
   - from:
     to: flow1
   - from: flow1
     to: Task2
     condition:
         in_parent:
           node: Task1
           parent_subflow: flow1
```
