### ISSUE TITLE
Introduce timeout configuration option for tasks

### ISSUE THREAD

**Issue by fridex** [selinon/selinon#31]
It would be nice to support task timeouts so task execution time can exceed:

```yaml
tasks:
  - name: 'Task1'
    import: 'myapp.tasks'
    timeout: 600
```

In that case a special exception would be raised (e.g. `selinon.TimeoutError`) and the timeout would be reported as task error (with respect to task's retry configuration).
